@startuml ConstructionDetailExport
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true
title 指标加工-》分部、分页指标导出逻辑整理\nPOST请求： /quotaPortalApi/portal/constructionDetail/all/export
actor       User       as user
control     ConstructionDetailController     as control1 #99FF99
control     ConstructionDetailService     as service1 #FF9966
control     quotaConstructionRest as control2 #99CCFF
control     subIndexQuantityRest as control3
collections ExcelExportDTO as EEDTO
user -> control1
control1 -> service1 : 将接收参数传入service层
service1 -> control2 : 调用得到项目列表树型接口
control2 --> service1
service1 -> control2 : 查询单项工程费用汇总
control2 --> service1
service1 -> control3 : 查询分部、分页列表
control3 --> service1
service1 -> service1 : 拼装前面查询参数到map中
service1 -> EEDTO : 将参数填入Excel导出实体类中
EEDTO -> EEDTO : 使用ExcelExport工具类\n将实体类写入Excel中
EEDTO --> service1 : 同步返回给用户
service1 --> control1
control1 --> user : 设置response属性
@enduml
